### ISSUE TITLE
Добавить в фигуры функцию, которая возвращает информацию о том, куда она может ходить 

### ISSUE THREAD

**Issue by teiuaz** [N1kla3/ChessUE#3]
Без создания отдельного класса сигнатура функции может выглядеть следующим образом.
```c++
vector<vector<Vector2>> GetStepCoordinates();
```
Возвращаться будет вектор векторов с координатами. Каждый вектор координат - это позволительные для этой фигуры координаты клеток для шага в одном направлении. Например у коня - 4 направления(в каждом по одной координате), у ладьи - также 4(но координат будет больше на каждое направление в зависимости от текущих координат фигуры). При этом конкретное направление не важно, те оно само по себе никак не будет использоваться, важен лишь тот факт, что это разные направления, эта необходимость описана далее.

Координаты в каждом векторе по направлению перечислены в порядке перемещения от самой фигуры к краям доски. Это важная информация, которая потом должна быть использована в борде для определения блокирующих перемещений для данной фигуры.

**Comment by N1kla3** [comment]
можно же и один вектор
